name: geph build

on:
  release:
    types:
      - published

jobs:
  build:
    if: ${{ github.event.release.tag_name == 'geph' }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ windows-latest, ubuntu-latest ]
        include:
          - os: windows-latest
            windows: stable-i686-pc-windows-msvc
    steps:
      - if: ${{ matrix.windows }}
        run: |
          rustup default ${{ matrix.windows }}
          rustup update

      - name: Build
        shell: bash
        run: |
          git clone https://github.com/geph-official/geph4-client
          cd geph4-client
          cargo update
          cargo build --release --locked
          rm target/release/*.d

      - name: Upload Release Asset
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: geph4-client/target/release/geph4-client*

      - if: ${{ matrix.windows }}
        uses: shogo82148/actions-upload-release-asset@v1
        with:
          upload_url: ${{ github.event.release.upload_url }}
          asset_path: geph4-client/windows-lib/WinDivert.dll
