name: httpproxy
on:
  workflow_dispatch:

jobs:
  prepare:
    runs-on: ubuntu-latest
    steps:
      - name: Delete Old Release
        uses: actions/github-script@v7
        with:
          script: |
            let release
            try {
              release = await github.rest.repos.getReleaseByTag({
                owner: context.repo.owner,
                repo: context.repo.repo,
                tag: 'httpproxy'
              })
            } catch(e) {
              console.error(e)
              return
            }
            await github.rest.repos.deleteRelease({
              owner: context.repo.owner,
              repo: context.repo.repo,
              release_id: release.data.id
            })
            await github.rest.git.deleteRef({
              owner: context.repo.owner,
              repo: context.repo.repo,
              ref: 'tags/'+release.data.tag_name
            })

  build:
    runs-on: ${{ matrix.os }}
    needs: prepare
    strategy:
      matrix:
        include:
          - os: windows-latest
            name: windows-amd64
          - os: ubuntu-latest
            name: linux-amd64
          - os: macos-latest
            name: macos-arm64
    steps:
      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: stable

      - name: Build
        shell: bash
        run: |
          mkdir -p release
          git clone https://github.com/sunshineplan/httpproxy
          cd httpproxy/service
          go build -ldflags "-s -w"

      - name: Move client binary (non-Windows)
        if: matrix.os != 'windows-latest'
        run: mv httpproxy/service/httpproxy release/httpproxy-${{ matrix.name }}

      - name: Move client binary (Windows)
        if: matrix.os == 'windows-latest'
        shell: bash
        run: mv httpproxy/service/httpproxy.exe release/httpproxy-${{ matrix.name }}.exe

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.name }}-latest
          path: release/httpproxy*

  release:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts
          merge-multiple: true

      - name: Create Release
        id: release
        uses: softprops/action-gh-release@v2
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: httpproxy
          name: httpproxy
          body: httpproxy
          files: artifacts/*
